### PR TITLE
Remove localization samples configs shorten path -vnext

### LINKED ISSUE #2731: Localization topic samples are not working on SB and sandbox
https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/localization

### PR DESCRIPTION
**Pull request by dobromirts**
Closes #2731

### CODE REVIEW

File: live-editing/configs/LocalizationConfigGenerator.ts [hunk 1]
```diff
@@ -5,62 +5,57 @@ import {
...
-            shortenComponentPathBy: "/localization-samples/"
+            })
         }));
 
         // localization sample 3
         configs.push(new Config({
             component: 'LocalizationSample3Component',
-            additionalFiles: ["src/app/data/nwindData.ts"],
-            additionalDependencies: ["igniteui-angular-i18n"],
+            additionalDependencies: ['igniteui-angular-i18n'],
```
Comment (zdrawku) [inline live-editing/configs/LocalizationConfigGenerator.ts:41]: additionalFiles should not be removed as the sample in stackblitz will return an error. Is there a reason to remove adding the nwindData.ts?

**Review by zdrawku — CHANGES_REQUESTED** [review]
I've noticed two problems, the first sample of the topic is not loaded because of missing package - its strange that the particular package is present ..
image

**Comment by dobromirts** [comment]
> The first sample of the topic is not loaded because of missing package - its strange that the particular package is present ..
> image

This behaviour is due to the usage of  resources as 'IgxResourceStrings'  which are provided from this package and when they are assigned to 'locales' property in the 'OnInit' stackblitz can not find and use this package anymore.

**Review by zdrawku — APPROVED** [review]
