### PR TITLE
Live Editing Documentation & TS lint fixes

### LINKED ISSUE #130: Create a live editing read me
### Description  
We should have a README.md file describing the live editing.

### LINKED ISSUE #215: Fix all TS Lint issues in live editing functionality

### PR DESCRIPTION
**Pull request by tiliev**
Closes #215, closes #130.

### CODE REVIEW

File: live-editing/configs/GridConfigGenerator.ts [hunk 1]
```diff
@@ -21,17 +10,29 @@ import {
...
-    IgxInputDirective,
     IgxToastModule
 } from "igniteui-angular/main";
-import { DataService } from "../../src/app/grid/services/data.service";
-import { LocalService } from "../../src/app/grid/grid-sample-2/grid-sample-2.component";
-import { GridContextmenuComponent } from "../../src/app/grid/grid-sorting-sample/grid-contextmenu/grid-contextmenu.component";
+import { FilteringSampleComponent } from "../../src/app/grid/grid-filtering-sample/grid-filtering-sample.component";
+import { PagingSampleComponent } from "../../src/app/grid/grid-paging-sample/grid-paging-sample.component";
+import { ResizingSampleComponent } from "../../src/app/grid/grid-resizing-sample/grid-resizing-sample.component";
+import { FinancialSampleComponent, LocalService } from "../../src/app/grid/grid-sample-2/grid-sample-2.component";
```
Comment (zdrawku) [inline live-editing/configs/GridConfigGenerator.ts]: The topic is perfect! Well done Tishe.

One thing that I've noticed is that Grid column resizing stackblitz stample is not loaded correctly.

I don't know why, but this sample is importing FinancialSampleComponent


image
