### PR TITLE
fix(grid-sample): return where is no data for summaries

### LINKED ISSUE #325: Exception is thrown when filtering return 0 records and custom summaries are enabled
### Description  
core.js:1448 ERROR TypeError: Cannot read property 'toFixed' of undefined exception is thrown when trying to filter "Athlete" column

### Steps to reproduce  

1. Open Boston Marathon 2018 sample
https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid.html
Also reproducible in production:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
2. Click filtering icon in "Athletes" column 
3. Start typing in filtering input
4. Observe the console

### Result  
What is the actual result after following the steps to reproduce?

### Expected result  
core.js:1448 ERROR TypeError: Cannot read property 'toFixed' of undefined expetion is thrown

### Attachments  
No exception to be thrown

### PR DESCRIPTION
**Pull request by Aleksandyr**
Closes #325

### CODE REVIEW

File: src/app/grid/grid.component.ts [hunk 1]
```diff
@@ -176,6 +176,10 @@ class CustomTopSpeedSummary extends IgxNumberSummaryOperand {
     }
 
     public operate(data?: any[]): IgxSummaryResult[] {
+        if (!data.length) {
```
Comment (mpavlinov) [inline src/app/grid/grid.component.ts]: @Aleksandyr If data is undefined this code will throw an error.

File: src/app/grid/grid.component.ts [hunk 2]
```diff
@@ -194,6 +198,10 @@ export class CustomBPMSummary extends IgxNumberSummaryOperand {
...
```
Comment (mpavlinov) [inline src/app/grid/grid.component.ts]: @Aleksandyr If data is undefined this code will throw an error.
