### PR TITLE
Demonstrating setOffset method in a drag/drop sample

### LINKED ISSUE #1550: Update the Drag and Drop sample to demonstrate the overlay's 'setOffset' method
### Description  
Demonstrate how to use the `setOffest` method in order to move the `overlay__content` container alongside with it's content.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/drag_drop.html
2. Navigate to "Dragging Using a Handle" section
3. Open the dialog and drag it
4. Inspect where the overlay content container is positioned

### Result  
The container is at the initial position

### Expected result  
The container should be dragged with the dialog

### Attachments  
screenshot

### PR DESCRIPTION
**Pull request by dafo**
Closes #1550

### CODE REVIEW

File: src/app/interactions/drag-drop/dialog-sample/drag-dialog-sample.component.ts [hunk 1]
```diff
@@ -41,4 +41,11 @@ export class DragDialogSampleComponent {
     }
     this.toggleFormDrag.setLocation(new IgxDragLocation(this.toggleStartPageX, this.toggleStartPageY));
   }
+
+  public onDragMove(e) {
+    const deltaX = e.nextPageX - e.pageX;
+    const deltaY = e.nextPageY - e.pageY;
+
```
Comment (wnvko) [inline src/app/interactions/drag-drop/dialog-sample/drag-dialog-sample.component.ts]:
```suggestion
    e.cancel = true;
```

Comment (wnvko) [reply src/app/interactions/drag-drop/dialog-sample/drag-dialog-sample.component.ts]: you should cancel the event
