### PR TITLE
fix(FinJSDemoComponent): Finjs category chart

### LINKED ISSUE #3111: Chart of the finjs grid is not themed and do not show anything
### Description  
The chart of the finjs grid is not themed and do not show anything 

### Steps to reproduce  

1. Open finjs grid
2. Change theme to dark
3. Click on chart button
FinTech Grid Dark theme1

### PR DESCRIPTION
**Pull request by katherinedragieva**
Closes #3111

### CODE REVIEW

File: projects/app-lob/src/app/grid-finjs/main.component.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export class FinJSDemoComponent implements OnDestroy {
     public darkTheme = false;
 
     public properties = ['price', 'country'];
-    public chartData: Stock[] = [];
+    public chartData: any[] = [];
```
Comment (hanastasov) [inline projects/app-lob/src/app/grid-finjs/main.component.ts:23]: Good practice is to always type, and type to `any` only if really really needed. Not sue if this is the case.

File: projects/app-lob/src/app/grid-finjs/main.component.ts [hunk 2]
```diff
@@ -86,7 +86,14 @@ export class FinJSDemoComponent implements OnDestroy {
     public setChartData(args: Stock[]): void {
         this.chartData = [];
         args.forEach(row => {
-            this.chartData.push(row);
+            this.finGrid.grid.data.filter(data => {
```
Comment (hanastasov) [inline projects/app-lob/src/app/grid-finjs/main.component.ts:89]: There is a forEach loop. and inside it there is filter, which again loops through all data records. Not a viable solution. This increases complexity and iterations a lot. Must be changed.

**Review by hanastasov — CHANGES_REQUESTED** [review]

**Comment by dobromirts** [comment]
The chart is still not themed based on the selected dark theme and preserves the default styles.
chart-theming

**Review by hanastasov — APPROVED** [review]

File: projects/app-lob/src/app/grid-finjs/main.component.ts [hunk 3]
```diff
@@ -85,10 +95,15 @@ export class FinJSDemoComponent implements OnDestroy {
 
     public setChartData(args: Stock[]): void {
         this.chartData = [];
-        args.forEach(row => {
-            this.chartData.push(row);
-            this.chart.notifyInsertItem(this.chartData, this.chartData.length - 1, row);
+        this.finGrid.grid.data.filter(data => {
```
Comment (hanastasov) [inline projects/app-lob/src/app/grid-finjs/main.component.ts:98]: Instead of going through all grid data and compare the id, grid API should be used for such cases. It is more intuitive and more readable.

**Review by hanastasov — CHANGES_REQUESTED** [review]
USe grid api instead

**Review by hanastasov — APPROVED** [review]
