### PR TITLE
fix(finjs): add option to hide theme switch for sample

### LINKED ISSUE #3188: Dark mode switch disappeared from the grid finjs sample
### Description  
There is no longer a dark mode switch in the finjs sample.

### Steps to reproduce  

1. Open https://www.infragistics.com/angular-demos-lob/grid-finjs

### Result  
No dark mode switch.

### Expected result  
The dark mode switch should be there.

### PR DESCRIPTION
**Pull request by Svetloslav15**
Close #3188, #3189

### CODE REVIEW

File: projects/app-lob/src/app/grid-finjs/controllers.component.ts [hunk 1]
```diff
@@ -60,6 +65,11 @@ export class ControllerComponent implements OnInit, OnDestroy {
             .subscribe(() => this.frequencyChanged.emit(this.intervalSlider.value as number));
         
         this.toast.positionSettings.verticalDirection = VerticalAlignment.Middle;
+
+        // Hide theme switcher
+        if (this.router.snapshot.queryParamMap.get('theme-switch')) {
```
Comment (hanastasov) [inline projects/app-lob/src/app/grid-finjs/controllers.component.ts:70]: It seems it does not matter what value is send for the theme-switch param.Even if ?theme-switch=true is send, button will be hidden, Let's respect the value sent.

**Review by hanastasov — CHANGES_REQUESTED** [review]

**Review by hanastasov — DISMISSED** [review]

**Review by zdrawku — APPROVED** [review]

**Comment by zdrawku** [comment]
@Svetloslav15 please cherry-pick these changes into vNext branch as well
