### PR TITLE
fix(grid-selection): Updating the use of rowSelectionChanging event i…

### LINKED ISSUE #3042: Grid rowSelectionChanging event samples issue
(rowSelectionChanging) event samples don't look right.
 - It's not typed
 - There doesn't seem to be such thing as event.cell
 - The sample doesn't do anything with it, so it's not showing how this event is useful.

image

### PR DESCRIPTION
**Pull request by IvanKitanov17**
Closes #3042

### CODE REVIEW

File: src/app/hierarchical-grid/hierarchical-grid-selection/hierarchical-grid-selection.component.ts [hunk 1]
```diff
@@ -34,11 +37,20 @@ export class HGridSelectionSampleComponent implements OnInit, OnDestroy {
 
     public selectCellSelectionMode(args) {
         this.selectionMode = this.selectionModes[args.index].label;
+        this.snackbarRowCount.close();
         this.snackbar.open();
+        this.selectedRowsCount = undefined;
+        this.selectedRowIndex = undefined;
     }
 
     public handleRowSelection(event) {
```
Comment (zdrawku) [inline src/app/hierarchical-grid/hierarchical-grid-selection/hierarchical-grid-selection.component.ts:46]: @IvanKitanov17 you've decided not to type the `rowSelection` event this time with `IRowSelectionEventArgs`?

Comment (IvanKitanov17) [reply src/app/hierarchical-grid/hierarchical-grid-selection/hierarchical-grid-selection.component.ts]: @zdrawku  It is re-added with the latest commit.

**Review by zdrawku — APPROVED** [review]
